//  Transmitter (sender)
basic.showString("SENDER")
radio.setGroup(56)
basic.forever(function on_forever() {
    led.toggle(4, 4)
    //  radio.send_number(input.acceleration(Dimension.X))
    //  radio.send_number(input.acceleration(Dimension.Y))
    //  radio.send_number(input.acceleration(Dimension.Z))
    radio.sendValue("x", input.acceleration(Dimension.X))
    radio.sendValue("y", input.acceleration(Dimension.Y))
    radio.sendValue("z", input.acceleration(Dimension.Z))
    basic.pause(200)
})
